nelmio_api_doc:
  documentation:
    servers:
      - url: http://127.0.0.1:8000
        description: SwaggerHub API Auto Mocking
    info:
      title: LegalOne Technical Challenge
      description: Log stream analysis API
      version: 1.0.0
      contact:
        email: marko.schilde@legal.one
      license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
  areas:
    path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
      - /count
