version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://symfony_user:secret@db/symfony_db
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    command: ["bash", "-c", "service cron start && symfony server:start --no-tls"]

volumes:
  pg_data:
